node {
    stage('SCM') {
        echo 'Gathering code from version control'
    }
    stage('Build') {
        echo 'Building....'
        echo 'Building nerw feature'
    }
    stage('Test') {
        echo 'Testing....'
    }
    stage('Deploy') {
        echo 'Deploying....'
    }
}